import type { Product1688 } from "./api"

export interface MultilingualProduct extends Product1688 {
  title_en?: string
  title_zh?: string
}

// Comprehensive mock product data with Vietnamese names and realistic details
export const MOCK_PRODUCTS: Record<string, MultilingualProduct> = {
  // Fashion - Áo polo nam
  "123456789": {
    item_id: "123456789",
    title: "Áo polo nam cao cấp vải cotton thoáng mát phối sọc ngang thời trang",
    title_en: "Men's Premium Cotton Polo Shirt with Horizontal Stripes",
    title_zh: "男士高级棉质Polo衫横条纹时尚款",
    price: "73900",
    original_price: "150000",
    main_imgs: [
      "/men-polo-shirt-striped-green.jpg",
      "/men-polo-shirt-blue.jpg",
      "/men-polo-shirt-white.jpg",
      "/men-polo-shirt-detail.jpg",
    ],
    shop_name: "Thời Trang Nam Cao Cấp",
    seller_id: "shop001",
    sales: 991962630,
    category_name: "Thời trang nam",
  },

  // Electronics - Máy bán hàng
  "987654321": {
    item_id: "987654321",
    title: "Nhà máy bán buôn bộ bán buôn sầu bánh mì đầu đỏ 100 viên/hộp sầu Lưỡi mỏi giá mỗi hộp",
    title_en: "Wholesale Food Packaging Machine 100 pieces/box",
    title_zh: "批发食品包装机100粒/盒",
    price: "24635",
    original_price: "45000",
    main_imgs: ["/food-packaging-machine.jpg", "/packaging-machine-detail.jpg"],
    shop_name: "Thiết Bị Công Nghiệp",
    seller_id: "shop002",
    sales: 714116192,
    category_name: "Thiết bị điện tử",
  },

  // Art supplies - Bút vẽ
  "456789123": {
    item_id: "456789123",
    title: "Mặt dây chuyền nhỏ màu nổ hoa sĩ nhỏ bảng về graffiti mini móc khóa xe hơi túi cặp đồ trang trí",
    title_en: "Colorful Graffiti Mini Markers with Car Key Clip",
    title_zh: "彩色涂鸦迷你马克笔带车钥匙扣",
    price: "15918",
    original_price: "28000",
    main_imgs: ["/graffiti-markers-colorful.jpg", "/art-markers-set.jpg"],
    shop_name: "Văn Phòng Phẩm Sáng Tạo",
    seller_id: "shop003",
    sales: 534197655,
    category_name: "Văn phòng phẩm",
  },

  // Sports - Giày bóng rổ
  "789123456": {
    item_id: "789123456",
    title: "Giày bóng rổ mặt da Curry xuyên biên giới màu mới giày thể thao nam chống trượt chống mài mòn",
    title_en: "Curry High-Top Leather Basketball Shoes Men's Sports Sneakers",
    title_zh: "库里高帮皮质篮球鞋男士运动鞋",
    price: "238770",
    original_price: "450000",
    main_imgs: ["/curry-basketball-shoes-white.jpg", "/basketball-shoes-side-view.jpg", "/basketball-shoes-sole.jpg"],
    shop_name: "Giày Thể Thao Chính Hãng",
    seller_id: "shop004",
    sales: 516173434,
    category_name: "Giày thể thao",
  },

  // Home & Security - Két sắt
  "321654987": {
    item_id: "321654987",
    title: "Thép tốc độ cao hoàn toàn mới món tháng khoan xoắn hộp kim titan đen pin thép không gỉ",
    title_en: "High-Speed New Steel Safe Box Titan Black Pin Stainless Steel",
    title_zh: "高速全新钢质安全箱钛黑金属扣不锈钢",
    price: "26151",
    original_price: "48000",
    main_imgs: ["/steel-safe-box-black.jpg", "/safe-box-interior.jpg"],
    shop_name: "Thiết Bị An Ninh",
    seller_id: "shop005",
    sales: 425890123,
    category_name: "Đồ gia dụng",
  },

  // Women's Fashion - Áo sơ mi nữ
  "654987321": {
    item_id: "654987321",
    title: "Áo sơ mi nữ tay dài vải lụa cao cấp phong cách Hàn Quốc thanh lịch",
    title_en: "Women's Long Sleeve Silk Blouse Korean Style Premium",
    title_zh: "女士长袖丝绸衬衫韩版高级款",
    price: "89500",
    original_price: "165000",
    main_imgs: ["/women-silk-blouse-white.jpg", "/women-blouse-pink.jpg", "/placeholder.svg?height=600&width=600"],
    shop_name: "Thời Trang Nữ Hàn Quốc",
    seller_id: "shop006",
    sales: 823456789,
    category_name: "Thời trang nữ",
  },

  // Shoes - Giày sneaker
  "147258369": {
    item_id: "147258369",
    title: "Giày sneaker nam nữ đế cao phong cách ulzzang Hàn Quốc hot trend 2024",
    title_en: "Unisex Ulzzang Style High-Heel Sneakers Korean Trend 2024",
    title_zh: "男女同款ulzzang风格高跟运动鞋韩风潮流2024",
    price: "125000",
    original_price: "220000",
    main_imgs: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    shop_name: "Giày Sneaker Hàn Quốc",
    seller_id: "shop007",
    sales: 654321987,
    category_name: "Giày dép",
  },

  // Electronics - Tai nghe
  "369258147": {
    item_id: "369258147",
    title: "Tai nghe bluetooth 5.0 không dây chống ồn pin trâu 40h âm thanh HiFi",
    title_en: "Bluetooth 5.0 Wireless Noise-Canceling Headphones 40h Battery Life HiFi",
    title_zh: "蓝牙5.0无线降噪耳机40小时电池寿命HiFi",
    price: "156000",
    original_price: "280000",
    main_imgs: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    shop_name: "Điện Tử Thông Minh",
    seller_id: "shop008",
    sales: 445678901,
    category_name: "Thiết bị điện tử",
  },

  // Flash Sales Products
  "111222333": {
    item_id: "111222333",
    title: "Áo Polo Nam Áo phông cộc tay trào lưu cổ bẻ mùa hè phong cách Hàn Quốc",
    title_en: "Men's Summer Polo Shirt Korean Style Short Sleeve",
    title_zh: "男士夏季Polo衫韩版短袖翻领",
    price: "38000",
    original_price: "55000",
    main_imgs: ["/white-polo-shirt-gradient.jpg"],
    shop_name: "Thời Trang Nam Cao Cấp",
    seller_id: "shop009",
    sales: 17840,
    category_name: "Thời trang nam",
  },

  "444555666": {
    item_id: "444555666",
    title: "Áo thun nam ngắn tay mùa hè đánh cho người trung niên và thanh niên",
    title_en: "Men's Summer Short Sleeve T-Shirt for Middle-aged and Young",
    title_zh: "男士夏季短袖T恤中青年款",
    price: "19500",
    original_price: "23500",
    main_imgs: ["/green-striped-polo-shirt.jpg"],
    shop_name: "Áo Polo Nam",
    seller_id: "shop010",
    sales: 11225,
    category_name: "Thời trang nam",
  },

  "777888999": {
    item_id: "777888999",
    title: "Mùa hè nam cao cấp công sở ngắn tay áo bó hộ lao động áo phông",
    title_en: "Men's Premium Office Short Sleeve Work Polo Shirt",
    title_zh: "男士高级办公短袖工作Polo衫",
    price: "54000",
    original_price: "61500",
    main_imgs: ["/couple-blue-polo-shirts.jpg"],
    shop_name: "Áo Đồng Phục",
    seller_id: "shop011",
    sales: 11149,
    category_name: "Thời trang nam",
  },

  "101112131": {
    item_id: "101112131",
    title: "Áo Polo lớp không khí cotton 300g cao cấp áo Sơ Mi Nam Dài Tay",
    title_en: "Men's Premium 300g Cotton Long Sleeve Polo Shirt",
    title_zh: "男士高级300克棉质长袖Polo衫",
    price: "63000",
    original_price: "81000",
    main_imgs: ["/gray-long-sleeve-polo.jpg"],
    shop_name: "Áo Polo Cao Cấp",
    seller_id: "shop012",
    sales: 7530,
    category_name: "Thời trang nam",
  },

  "141516171": {
    item_id: "141516171",
    title: "Áo ngoại thương Paul áo polo nam tay ngắn áo phông nam cao cấp",
    title_en: "Paul Brand Men's Premium Short Sleeve Polo Shirt",
    title_zh: "保罗品牌男士高级短袖Polo衫",
    price: "22000",
    original_price: "23200",
    main_imgs: ["/white-polo-shirt-with-gold-logo.jpg"],
    shop_name: "Thương Hiệu Quốc Tế",
    seller_id: "shop013",
    sales: 5373,
    category_name: "Thời trang nam",
  },

  "181920212": {
    item_id: "181920212",
    title: "Áo Polo nam áo dài tay sọc hai màu giá cổ bẻ giữ ấm lót nhung",
    title_en: "Men's Two-Tone Striped Long Sleeve Warm Polo Sweater",
    title_zh: "男士双色条纹长袖保暖Polo毛衣",
    price: "29000",
    original_price: "37800",
    main_imgs: ["/beige-checkered-polo-sweater.jpg"],
    shop_name: "Áo Len Nam",
    seller_id: "shop014",
    sales: 3052,
    category_name: "Thời trang nam",
  },

  // Shoes Category
  "222333444": {
    item_id: "222333444",
    title: "Giày thể thao nam nữ running thoáng khí đế êm chạy bộ marathon",
    title_en: "Unisex Running Shoes Comfortable Sole Marathon",
    title_zh: "男女同款跑步鞋透气软底马拉松",
    price: "165000",
    original_price: "320000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Giày Thể Thao Chuyên Nghiệp",
    seller_id: "shop015",
    sales: 889900112,
    category_name: "Giày thể thao",
  },

  "555666777": {
    item_id: "555666777",
    title: "Giày da nam công sở cao cấp mũi nhọn lịch lãm sang trọng",
    title_en: "Men's Premium Leather Business Shoes Pointed Toe Elegant",
    title_zh: "男士高级皮质商务鞋尖头优雅款",
    price: "245000",
    original_price: "480000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Giày Da Công Sở",
    seller_id: "shop016",
    sales: 334455667,
    category_name: "Giày da",
  },

  "888999000": {
    item_id: "888999000",
    title: "Dép sandal nữ quai ngang đế bệt phong cách Hàn Quốc đi biển",
    title_en: "Women's Cross Strap Sandals Korean Style Beach",
    title_zh: "女士交叉带沙滩凉鞋韩风款",
    price: "78000",
    original_price: "150000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Dép Sandal Thời Trang",
    seller_id: "shop017",
    sales: 556677889,
    category_name: "Dép sandal",
  },

  "121314151": {
    item_id: "121314151",
    title: "Giày boot nữ cổ cao da lộn phong cách vintage retro",
    title_en: "Women's High Heel Leather Boot Vintage Retro Style",
    title_zh: "女士高跟皮质靴复古风格",
    price: "285000",
    original_price: "550000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Giày Boot Nữ Cao Cấp",
    seller_id: "shop018",
    sales: 445566778,
    category_name: "Giày boot",
  },

  // Keyboards Category
  "161718192": {
    item_id: "161718192",
    title: "Bàn phím cơ gaming RGB mechanical switch blue 87 phím",
    title_en: "RGB Mechanical Switch Blue 87-Key Gaming Keyboard",
    title_zh: "RGB机械开关蓝色87键游戏键盘",
    price: "385000",
    original_price: "750000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Bàn Phím Cơ Gaming",
    seller_id: "shop019",
    sales: 667788990,
    category_name: "Bàn phím",
  },

  "202122232": {
    item_id: "202122232",
    title: "Bàn phím không dây bluetooth đa thiết bị pin sạc 3 tháng",
    title_en: "Wireless Bluetooth Multi-Device Keyboard 3-Month Battery Life",
    title_zh: "无线蓝牙多设备键盘3个月电池寿命",
    price: "195000",
    original_price: "380000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Phụ Kiện Văn Phòng",
    seller_id: "shop020",
    sales: 778899001,
    category_name: "Bàn phím",
  },

  "242526272": {
    item_id: "242526272",
    title: "Bàn phím mini 60% custom keycap PBT hot swap switch",
    title_en: "60% Custom Keycap PBT Hot Swap Switch Mini Keyboard",
    title_zh: "60%自定义键帽PBT热插拔开关迷你键盘",
    price: "425000",
    original_price: "850000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Custom Keyboard Shop",
    seller_id: "shop021",
    sales: 334455667,
    category_name: "Bàn phím",
  },

  "282930313": {
    item_id: "282930313",
    title: "Bàn phím gaming có dây LED đơn sắc chống nước giá rẻ",
    title_en: "Wired LED Single Color Water-Resistant Gaming Keyboard Affordable",
    title_zh: "有线LED单色防水游戏键盘经济实惠",
    price: "145000",
    original_price: "280000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Gaming Gear Budget",
    seller_id: "shop022",
    sales: 889900112,
    category_name: "Bàn phím",
  },

  // Women's Fashion
  "323334353": {
    item_id: "323334353",
    title: "Váy maxi dài hoa nhí vintage phong cách Pháp thanh lịch",
    title_en: "Women's Vintage French Style Maxi Dress with Large Flowers",
    title_zh: "女士复古法式大花 maxi连衣裙",
    price: "185000",
    original_price: "360000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Váy Đầm Nữ Cao Cấp",
    seller_id: "shop023",
    sales: 556677889,
    category_name: "Thời trang nữ",
  },

  "363738394": {
    item_id: "363738394",
    title: "Quần jean nữ ống rộng lưng cao phong cách Hàn Quốc trẻ trung",
    title_en: "Women's Wide Leg High Waist Jean Pants Korean Style Trendy",
    title_zh: "女士宽松高腰牛仔裤韩风时尚款",
    price: "165000",
    original_price: "320000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Quần Jean Nữ",
    seller_id: "shop024",
    sales: 667788990,
    category_name: "Thời trang nữ",
  },

  "404142434": {
    item_id: "404142434",
    title: "Áo khoác cardigan len nữ dáng dài ấm áp mùa đông",
    title_en: "Women's Long-Sleeve Warm Cardigan Sweater Wool",
    title_zh: "女士长袖保暖羊毛开衫",
    price: "195000",
    original_price: "380000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Áo Len Nữ",
    seller_id: "shop025",
    sales: 445566778,
    category_name: "Thời trang nữ",
  },

  "444546474": {
    item_id: "444546474",
    title: "Set đồ nữ áo croptop + chân váy xòe phối màu xinh xắn",
    title_en: "Women's Croptop + Flared Skirt Set Colorful Fashion",
    title_zh: "女士露脐上衣+喇叭裙套装彩色时尚款",
    price: "145000",
    original_price: "280000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Set Đồ Nữ Hàn Quốc",
    seller_id: "shop026",
    sales: 778899001,
    category_name: "Thời trang nữ",
  },

  // Men's Fashion
  "484950515": {
    item_id: "484950515",
    title: "Áo thun nam basic cotton 100% form rộng unisex streetwear",
    title_en: "Men's Basic Cotton 100% Unisex Streetwear T-Shirt",
    title_zh: "男士基本100%棉质男女同款街头T恤",
    price: "85000",
    original_price: "165000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Áo Thun Nam Streetwear",
    seller_id: "shop027",
    sales: 889900112,
    category_name: "Thời trang nam",
  },

  "525354555": {
    item_id: "525354555",
    title: "Quần kaki nam ống suông túi hộp phong cách công sở lịch sự",
    title_en: "Men's Slim Trousers with Pouch Office Style Casual",
    title_zh: "男士紧身裤带口袋办公风格休闲款",
    price: "175000",
    original_price: "340000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Quần Kaki Nam",
    seller_id: "shop028",
    sales: 556677889,
    category_name: "Thời trang nam",
  },

  "565758596": {
    item_id: "565758596",
    title: "Áo sơ mi nam dài tay trắng công sở vải kate cao cấp",
    title_en: "Men's Premium Long Sleeve White Office Shirt Kate Cotton",
    title_zh: "男士高级长袖白色办公衬衫凯特棉",
    price: "155000",
    original_price: "300000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Áo Sơ Mi Nam Công Sở",
    seller_id: "shop029",
    sales: 667788990,
    category_name: "Thời trang nam",
  },

  "606162636": {
    item_id: "606162636",
    title: "Áo khoác bomber nam 2 lớp chống gió chống nước phong cách",
    title_en: "Men's Two-Layer Bomber Jacket Wind-Resistant Water-Proof Style",
    title_zh: "男士两层防风防水夹克时尚款",
    price: "265000",
    original_price: "520000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Áo Khoác Nam",
    seller_id: "shop030",
    sales: 445566778,
    category_name: "Thời trang nam",
  },

  // Kids Fashion
  "646566676": {
    item_id: "646566676",
    title: "Bộ đồ trẻ em cotton mềm mại họa tiết hoạt hình dễ thương",
    title_en: "Soft Cotton Kids' Fashion Set with Cute Cartoon Patterns",
    title_zh: "柔软棉质儿童时尚套装带可爱卡通图案",
    price: "95000",
    original_price: "185000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Thời Trang Trẻ Em",
    seller_id: "shop031",
    sales: 778899001,
    category_name: "Thời trang trẻ em",
  },

  "686970717": {
    item_id: "686970717",
    title: "Váy công chúa bé gái dự tiệc ren hoa xinh xắn cao cấp",
    title_en: "Beautiful Lace Princess Dress for Little Girls High Quality",
    title_zh: "漂亮的蕾丝公主裙小女孩高品质",
    price: "185000",
    original_price: "360000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Váy Đầm Bé Gái",
    seller_id: "shop032",
    sales: 334455667,
    category_name: "Thời trang trẻ em",
  },

  "727374757": {
    item_id: "727374757",
    title: "Áo khoác hoodie trẻ em unisex nỉ bông ấm áp mùa đông",
    title_en: "Unisex Kids' Hoodie Warm Wool Sweater Winter",
    title_zh: "男女同款儿童羊毛连帽衫保暖冬季款",
    price: "125000",
    original_price: "240000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Áo Khoác Trẻ Em",
    seller_id: "shop033",
    sales: 556677889,
    category_name: "Thời trang trẻ em",
  },

  "767778798": {
    item_id: "767778798",
    title: "Quần jean bé trai ống đứng co giãn thoải mái năng động",
    title_en: "Elastic Stand-Up Jean Pants for Little Boys Comfortable and Active",
    title_zh: "弹性直筒牛仔裤小男孩舒适时尚",
    price: "105000",
    original_price: "205000",
    main_imgs: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    shop_name: "Quần Áo Bé Trai",
    seller_id: "shop034",
    sales: 667788990,
    category_name: "Thời trang trẻ em",
  },

  // Women's Fashion Products for Product Grid
  women001: {
    item_id: "women001",
    title: "Áo thun hở rốn nữ Âu Mỹ xuyên biên giới áo dáu sầu",
    title_en: "Women's Crop Top American Style Cross-border Fashion",
    title_zh: "女士露脐上衣欧美跨境时尚款",
    price: "9900",
    original_price: "12500",
    main_imgs: ["/white-crop-top.jpg"],
    shop_name: "Thời Trang Nữ Cao Cấp",
    seller_id: "shop_women",
    sales: 22214,
    category_name: "Thời trang nữ",
  },

  women002: {
    item_id: "women002",
    title: "HR25015 Quần áo phụ nữ Âu Mỹ khóa cao su thật lưu động áo",
    title_en: "HR25015 Women's European American Style Flowing Dress",
    title_zh: "HR25015女士欧美风格流动连衣裙",
    price: "61000",
    original_price: "77000",
    main_imgs: ["/colorful-women-dresses.jpg"],
    shop_name: "Thời Trang Nữ Quốc Tế",
    seller_id: "shop_women",
    sales: 10833,
    category_name: "Thời trang nữ",
  },

  women003: {
    item_id: "women003",
    title: "Chân Áo và Mỹ xuyên biên giới Amazon wish Ngoại thương",
    title_en: "Amazon Wish Cross-border Women's Ethnic Blouse",
    title_zh: "亚马逊Wish跨境女士民族风上衣",
    price: "24000",
    original_price: "30000",
    main_imgs: ["/blue-ethnic-blouse.jpg"],
    shop_name: "Amazon Fashion",
    seller_id: "shop_women",
    sales: 10020,
    category_name: "Thời trang nữ",
  },

  women004: {
    item_id: "women004",
    title: "Áo khoác cardigan nữ màu xanh dương Amazon mới",
    title_en: "Women's Blue Denim Cardigan Amazon New Style",
    title_zh: "女士蓝色牛仔开衫亚马逊新款",
    price: "59000",
    original_price: "75000",
    main_imgs: ["/blue-denim-cardigan.jpg"],
    shop_name: "Amazon Fashion",
    seller_id: "shop_women",
    sales: 6210,
    category_name: "Thời trang nữ",
  },

  women005: {
    item_id: "women005",
    title: "Amazon Châu Âu và Mỹ bộ đồ thường ngày của phụ nữ",
    title_en: "Amazon European American Women's Casual Jumpsuit",
    title_zh: "亚马逊欧美女士休闲连体裤",
    price: "43000",
    original_price: "54000",
    main_imgs: ["/magenta-jumpsuit.jpg"],
    shop_name: "Amazon Fashion",
    seller_id: "shop_women",
    sales: 5294,
    category_name: "Thời trang nữ",
  },

  women006: {
    item_id: "women006",
    title: "Áo len đệt kim cổ tròn nhỏ phối màu thời trang 100% cotton",
    title_en: "Women's Colorful Round Neck Knit Sweater 100% Cotton",
    title_zh: "女士彩色圆领针织毛衣100%棉",
    price: "72000",
    original_price: "90000",
    main_imgs: ["/colorful-sweaters.jpg"],
    shop_name: "Áo Len Nữ",
    seller_id: "shop_women",
    sales: 5198,
    category_name: "Thời trang nữ",
  },

  women007: {
    item_id: "women007",
    title: "Trang phục nữ trung niên và cao tuổi trang phục thời trang",
    title_en: "Middle-aged and Elderly Women's Fashion Sweater with Bow",
    title_zh: "中老年女士时尚蝴蝶结毛衣",
    price: "49000",
    original_price: "62000",
    main_imgs: ["/beige-sweater-with-bow.jpg"],
    shop_name: "Thời Trang Trung Niên",
    seller_id: "shop_women",
    sales: 5034,
    category_name: "Thời trang nữ",
  },

  women008: {
    item_id: "women008",
    title: "Áo phông nữ ngắn tay màu tương phản 100% cotton",
    title_en: "Women's Contrast Color Short Sleeve T-Shirt 100% Cotton",
    title_zh: "女士撞色短袖T恤100%棉",
    price: "13000",
    original_price: "16500",
    main_imgs: ["/short-sleeve-pink-tshirt.jpg"],
    shop_name: "Áo Thun Nữ Basic",
    seller_id: "shop_women",
    sales: 4754,
    category_name: "Thời trang nữ",
  },

  women009: {
    item_id: "women009",
    title: "Áo thun cộc tay kiểu nữ thời trang cao cấp thể thao",
    title_en: "Women's Premium Fashion Sports Short Sleeve Polo Shirt",
    title_zh: "女士高级时尚运动短袖Polo衫",
    price: "52000",
    original_price: "65000",
    main_imgs: ["/polo-shirts-collection.jpg"],
    shop_name: "Áo Polo Nữ",
    seller_id: "shop_women",
    sales: 4033,
    category_name: "Thời trang nữ",
  },

  women010: {
    item_id: "women010",
    title: "Xuyên biên giới Amazon AliExpress mới của phụ nữ",
    title_en: "Cross-border Amazon AliExpress Women's New Floral Maxi Dress",
    title_zh: "跨境亚马逊速卖通女士新款花卉长裙",
    price: "36000",
    original_price: "45000",
    main_imgs: ["/floral-maxi-dresses.jpg"],
    shop_name: "Amazon AliExpress",
    seller_id: "shop_women",
    sales: 3238,
    category_name: "Thời trang nữ",
  },

  // Nike Brand Products
  nike001: {
    item_id: "nike001",
    title: "Giày bóng rổ cao cổ Nike Guan aj312 Giày nam Putian Giày thể thao nam",
    title_en: "Nike High-Top Basketball Shoes AJ312 Men's Sports Sneakers",
    title_zh: "耐克高帮篮球鞋AJ312男士运动鞋",
    price: "160000",
    original_price: "380000",
    main_imgs: ["/nike-shoe-gray-white.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 23,
    category_name: "Giày thể thao",
  },

  nike002: {
    item_id: "nike002",
    title: "Giày Putian giày bóng rổ cao cổ AJ1 nguyên bản giày thể thao nam tây Joe Jordan",
    title_en: "Original AJ1 High-Top Basketball Shoes Men's Jordan Sneakers",
    title_zh: "原版AJ1高帮篮球鞋男士乔丹运动鞋",
    price: "234680",
    original_price: "560000",
    main_imgs: ["/nike-shoe-multi-color.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 209,
    category_name: "Giày thể thao",
  },

  nike003: {
    item_id: "nike003",
    title: "Giày nguyên bản cao cổ aj1 giày Putian giày thể thao nam cao cấp",
    title_en: "Original High-Top AJ1 Premium Men's Basketball Sneakers",
    title_zh: "原版高帮AJ1高级男士篮球运动鞋",
    price: "298000",
    original_price: "710000",
    main_imgs: ["/nike-shoe-black-white.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 6,
    category_name: "Giày thể thao",
  },

  nike004: {
    item_id: "nike004",
    title: "Giày chạy bộ thể thao thoáng khí mùa hè màu mới giày thể thao nam",
    title_en: "Summer Breathable Running Sports Shoes Men's New Color Sneakers",
    title_zh: "夏季透气跑步运动鞋男士新色运动鞋",
    price: "55000",
    original_price: "130000",
    main_imgs: ["/nike-shoe-teal-black.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 6,
    category_name: "Giày thể thao",
  },

  nike005: {
    item_id: "nike005",
    title: "Giày chạy bộ ba thể hạ London chất lượng cao giày thể thao nam giày nam",
    title_en: "High Quality London Style Running Shoes Men's Sports Sneakers",
    title_zh: "高品质伦敦风格跑步鞋男士运动鞋",
    price: "55000",
    original_price: "130000",
    main_imgs: ["/nike-shoe-black-white-2.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 0,
    category_name: "Giày thể thao",
  },

  nike006: {
    item_id: "nike006",
    title: "Giày trượt ván nam nữ giá trị giá thể thao điền từ thông cách thể thao",
    title_en: "Unisex Skateboard Shoes Value Sports Casual Sneakers",
    title_zh: "男女滑板鞋超值运动休闲鞋",
    price: "20580",
    original_price: "49000",
    main_imgs: ["/nike-shoe-white-blue.jpg"],
    shop_name: "Nike Official Store",
    seller_id: "nike_shop",
    sales: 20,
    category_name: "Giày thể thao",
  },
}

// Function to get mock product by ID
export function getMockProduct(id: string): MultilingualProduct | null {
  return MOCK_PRODUCTS[id] || null
}

// Function to get multiple mock products
export function getMockProducts(ids: string[]): MultilingualProduct[] {
  return ids.map((id) => getMockProduct(id)).filter((p): p is MultilingualProduct => p !== null)
}
